name: SAEED-BOT-RUN

on:
  push:
    branches: [ main, master ]
  schedule:
    - cron: '0 */6 * * *' # يعيد التشغيل كل 6 ساعات لضمان عدم التوقف
  workflow_dispatch: # يسمح لك بتشغيله يدوياً

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # نسخة حديثة ومستقرة

      - name: Install Dependencies
        run: npm install

      - name: Start SAEED-BOT
        run: node .
        env:
          NODE_OPTIONS: "--max_old_space_size=2048"
